_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  SOURCE_DOMAIN:
    TRAIN: ("itri-taiwan-416_train",)
  TARGET_DOMAIN:
    TRAIN: ("tokyo-320-v2_train",)
  TEST: ("tokyo-320_test",)
MODEL:
  META_ARCHITECTURE: "SWDARCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_da_backbone"
    FREEZE_AT: 1
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  KEYPOINT_ON: False
  MASK_ON: False
  DOMAIN_ADAPTATION_ON: True
  ROI_HEADS:
    NAME: "DAROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 3
    CONTEXT_REGULARIZATION_FEATURES: ['local_head_feature', 'global_head_feature']
    CONTEXT_REGULARIZATION_ON: True
  ROI_BOX_HEAD:
    FC_DIM: 256
  DA_HEADS:
    LOCAL_ALIGNMENT_ON: False
    GLOBAL_ALIGNMENT_ON: True
    GAMMA: 3.0
SOLVER:
  IMS_PER_BATCH: 1 # batch size
  LR_SCHEDULER_NAME: WarmupCosineLR
  STEPS: (60000, 100000)
  BASE_LR: 0.001
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
FEWSHOT_TUNING:
  DOMAIN_ADAPTATION_TUNING: False
  MODEL:
    BACKBONE_FROZEN: False
    DA_HEADS_FROZEN: True
  DATASETS:
    SOURCE_DOMAIN:
      TRAIN: ("tokyo-320-v2-val",)
    TARGET_DOMAIN:
      TRAIN: ("itri-taiwan-416-val",)
    TRAIN: ("tokyo-320-v2-val",)
    TEST: ("tokyo-320_test",)
  SOLVER:
    IMS_PER_BATCH: 1 # batch size
    LR_SCHEDULER_NAME: WarmupCosineLR
    STEPS: (4000, 6000)
    BASE_LR: 0.00001
    MAX_ITER: 15000
    CHECKPOINT_PERIOD: 1000
  TEST:
    EVAL_PERIOD: 1000
