_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  SOURCE_DOMAIN:
    TRAIN: ("itri-taiwan-416_train",)
  TARGET_DOMAIN:
    TRAIN: ("tokyo-320-v2_train",)
  TEST: ("tokyo-320_test",)
MODEL:
  META_ARCHITECTURE: "SWDARCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_da_backbone"
    FREEZE_AT: 1
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  KEYPOINT_ON: False
  MASK_ON: False
  ROI_HEADS:
    NAME: "DAStandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 3
    REGULARIZATION_FEATURES: ["local feature", "global feature"]
  ROI_BOX_HEAD:
    FC_DIM: 256
DA_HEAD:
  DOMAIN_ADAPTATION_ON: True
  GAMMA: 3.0
SOLVER:
  IMS_PER_BATCH: 1 # batch size
  BASE_LR: 0.001
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 10000